require("core.options")
require("core.keymaps")
require("core.templates")
require("core.comment_style")
require("plugins.plugins-setup")
require("plugins.treesitter")

-- require("plugins.vscode_theme")
require("plugins.everforest")
require("plugins.lualine")
require("plugins.colorizer")
require("plugins.gitsigns")
require("plugins.rainbow-delimiters")
require("plugins.nvim-web-devicons")
require("plugins.table_mode")
require("plugins.telescope")
require("plugins.language-server")
require("plugins.nvim-ts-autotag")
require("plugins.cmp")

